ruby-app/config/routes.rb
# # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :meetings
  devise_for :users

  authenticated :user, lambda { |u| !u.admin? } do
    root 'patients#index', as: :user_root
  end

  authenticated :user, lambda { |u| u.admin? } do
    root 'admins#index', as: :admin_root
  end

  # For non-authenticated users, redirect them to a specific page, like a login page or a welcome page
  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :assessments, only: [:edit, :update]



  get '/search', to: "admins#search"

  resources :forms, controller: 'patients' do
    member do
      get 'edit_1', to: 'patients#edit_1'
      patch 'edit_1', to: 'patients#update_1'
      get 'edit_2', to: 'patients#edit_2'
      patch 'edit_2', to: 'patients#update_2'
      get 'edit_3', to: 'patients#edit_3'
      patch 'edit_3', to: 'patients#update_3'
      get 'edit_4', to: 'patients#edit_4'
      patch 'edit_4', to: 'patients#update_4'
      get 'edit_5', to: 'patients#edit_5'
      patch 'edit_5', to: 'patients#update_5'
      get 'edit_physical_assessment', to: 'admins#_physical_assessment'
      patch 'edit_physical_assessment', to: 'admins#update_physical_assessment'
      get 'edit_mental_assessment', to: 'admins#_mental_assessment'
      patch 'edit_mental_assessment', to: 'admins#update_mental_assessment'
      get 'edit_environment_assessment', to: 'admins#_environment_assessment'
      patch 'edit_environment_assessment', to: 'admins#update_environment_assessment'
      get 'client_profile', to: 'admins#client_profile'
      patch 'client_profile', to: 'admins#update_client_profile'

      get 'edit_patient_assessment', to: 'admins#_patient_assessment'
      patch 'edit_patient_assessment', to: 'admins#update_patient_assessment'

      get 'physical_assessment', to: 'assessments#physical', as: 'physical_assessment'

      patch 'update_submission_status', to: 'patients#update_submission_status'
      post 'generate_signed_url', to: 'patients#generate_signed_url'
    end

    collection do
      get 'edit_1', to: 'patients#edit_1'
      post 'edit_1', to: 'patients#update_1_collection'
      get 'edit_2', to: 'patients#edit_2'
      post 'edit_2', to: 'patients#update_2_collection'
      get 'edit_3', to: 'patients#edit_3'
      post 'edit_3', to: 'patients#update_3_collection'
      get 'edit_4', to: 'patients#edit_4'
      post 'edit_4', to: 'patients#update_4_collection'
      get 'edit_5', to: 'patients#edit_5'
      post 'edit_5', to: 'patients#update_5_collection'
      get 'show_error', to: 'patients#show_error'
    end
  end
end

ruby-app/app/views/admins/NIU_environment_assessment.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninkatec Onboarding | Environment Assessment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

</head>

<body>
<div class="container">
  <p style="font-size:2em"><strong>Patient Assessment:</strong></p>
  <div class="row align-items-start">
    <div class="col-md-6">
      <p><strong>Environment Video:</strong></p>
        <% if @form.environment_video_file_name.present? %>
          <% gcs_service = GoogleCloudStorageService.new %>
          <% signed_url = gcs_service.generate_signed_url_for_viewing(@form.environment_video_file_name) %>
            <div class="video-container text-center mt-3">
              <%= video_tag signed_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
            </div>
      <% else %>
        <p>null</p>
      <% end %>
    </div>
    <div class="col-md-6">
      <p><strong>Environment Assessment: </strong><%= @form.environment_assessment.presence || "Pending Assessment" %></p>
      <%= form_with(model: @form, url: @form.persisted? ? edit_environment_assessment_form_path(@form) : edit_environment_assessment_forms_path, method: :patch, local: true, html: { multipart: true }) do |form| %>
      <fieldset>
        <div class="form-check form-check-inline">
          <%= form.radio_button :environment_assessment, "Good", class: "form-check-input", id: "good_env", checked: @form.environment_assessment == "Good", :required => false %>
          <%= form.label "good_env", class: "form-check-label", for: "good_env" do %>
            Good
          <% end %>
        </div>

        <div class="form-check form-check-inline">
          <%= form.radio_button :environment_assessment, "Fair", class: "form-check-input", id: "fair_env", checked: @form.environment_assessment == "Fair", :required => false %>
          <%= form.label "fair_env", class: "form-check-label", for: "fair_env" do %>
            Fair
          <% end %>
        </div>

        <div class="form-check form-check-inline">
          <%= form.radio_button :environment_assessment, "Poor", class: "form-check-input", id: "poor_env", checked: @form.environment_assessment == "Poor", :required => false %>
          <%= form.label "poor_env", class: "form-check-label", for: "poor_env" do %>
            Poor
          <% end %>
        </div>

        <div class="form-check form-check-inline">
          <%= form.radio_button :environment_assessment, "Detailed Assessment Needed", class: "form-check-input", id: "others_env", checked: !["Good", "Fair", "Poor", ""].include?(@form.environment_assessment) %>
          <%= form.label "others_env", class: "form-check-label", for: "others_env" do %>
            Detailed Assessment Needed:
          <% end %>
        </div>

        <br></br>

        <div class="form-check">
            
          <%= form.text_field :others_text, class: "form-control", id: "others_text_env", placeholder: "Detailed Assessment here", style: "font-style: italic; height: 175px; width: 300 px;", value: (!["Good", "Fair", "Poor", ""].include?(@form.environment_assessment)) ? @form.environment_assessment : ''%>
        </div>

        <div class="d-flex justify-content-center mt-5 mb-5">
          <%= form.submit "Save", name: "commit", value: "Save", class: "btn btn-lg rounded-pill btn-green me-2", id: "save_env", style: 'float: left; margin-right: 5px;'  %>

        </div>

        
      </fieldset>
    </div>
  </div>

<% end %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ruby-app/app/views/admins/NIU_mental_assessment.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninkatec Onboarding | Mental Assessment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
<body>
<div class="container">
  <p style="font-size:2em"><strong>Patient Assessment:</strong></p>
  <div class="row align-items-start">
    <div class="col-md-6">
      <p><strong>Mental Video:</strong></p>
        <% if @form.mental_video_file_name.present? %>
          <% gcs_service = GoogleCloudStorageService.new %>
          <% signed_url = gcs_service.generate_signed_url_for_viewing(@form.mental_video_file_name) %>
            <div class="video-container text-center mt-3">
              <%= video_tag signed_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
            </div>
      <% else %>
        <p>null</p>
      <% end %>
    </div>
    <div class="col-md-6">
      <p><strong>Mental Assessment: </strong>
        <br>
        <i><u>Transcript:</u></i>
        <br>
        <%= @form.mental_transcription.present? ? @form.mental_transcription.html_safe : "" %></p>
      <br>
      <p><strong>Animal Count: <br></strong><%= @form.animal_count.present? ? @form.animal_count : "" %></p>
      <br>
      <%= @form.mental_assessment.presence || "Pending Assessment" %>
      <%= form_with(model: @form, url: form.persisted? ? edit_mental_assessment_form_path(form) : edit_mental_assessment_forms_path, method: :patch, local: true, html: { multipart: true }) do |form| %>
      <fieldset>
        <div class="form-check form-check-inline">
          <%= form.radio_button :mental_assessment, "Good", class: "form-check-input", id: "good", checked: @form.mental_assessment == "Good", :required => false %>
          <%= form.label "good", class: "form-check-label", for: "good" do %>
            Good
          <% end %>
        </div>

      <div class="form-check form-check-inline">
        <%= form.radio_button :mental_assessment, "Fair", class: "form-check-input", id: "fair_mental", checked: @form.mental_assessment == "Fair" %>
        <%= form.label "fair_mental", class: "form-check-label", for: "fair_mental" do %>
          Fair
        <% end %>
      </div>

      <div class="form-check form-check-inline">
        <%= form.radio_button :mental_assessment, "Poor", class: "form-check-input", id: "poor_mental", checked: @form.mental_assessment == "Poor" %>
        <%= form.label "poor_mental", class: "form-check-label", for: "poor_mental" do %>
          Poor
        <% end %>
      </div>

      <div class="form-check form-check-inline">
        <%= form.radio_button :mental_assessment, "Detailed Assessment Needed", class: "form-check-input", id: "others_mental", checked: !["Good", "Fair", "Poor", ""].include?(@form.mental_assessment) %>
        <%= form.label "others_mental", class: "form-check-label", for: "others_mental" do %>
          Detailed Assessment Needed:
        <% end %>
      </div>

      <br>

      <div class="form-check">
        <%= form.text_field :others_text, class: "form-control", id: "others_text_mental", placeholder: "Detailed Assessment here", style: "font-style: italic; height: 175px; width: 300px;", value: (!["Good", "Fair", "Poor", ""].include?(@form.mental_assessment)) ? @form.mental_assessment : '' %>
      </div>

      <div class="d-flex justify-content-center mt-5 mb-5">
        <%= form.submit "Save", name: "commit", value: "Save", class: "btn btn-lg rounded-pill btn-green me-2", id: "save_mental", style: 'float: left; margin-right: 5px;' %>
      </div>
    </fieldset>
  <% end %>
  </div>
</div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ruby-app/app/views/admins/NIU_patient_assessmennt.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninkatec Onboarding | Complete Patient Assessment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="container">
  <h1>Patient Assessment for <%= @form.first_name %> <%= @form.last_name %></h1>

  <%= form_with(model: @form, url: @form.persisted? ? edit_patient_assessment_form_path(@form) : edit_patient_assessment_form_path, method: :patch, local: true, html: { multipart: true }) do |form| %>
    <!-- Physical Assessment Partial -->
    <%= render 'physical_assessment', form: form %>
    
    <!-- Mental Assessment Partial -->
    <%= render 'mental_assessment', form: form %>
    
    <!-- Environmental Assessment Partial -->
    <%= render 'environment_assessment', form: form %>
    
    <div class="d-flex justify-content-center mt-5 mb-5">
      <%= form.submit "Save", name: "commit", value: "Save", class: "btn btn-lg rounded-pill btn-green me-2", id: "save_phy", style: 'float: left; margin-right: 5px;'  %>
    </div>
  <% end %>
</div>
</body>
</html>

ruby-app/app/views/admins/NIU_physical_assessment.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninkatec Onboarding | Physical Assessment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

</head>

<body>
  <div class="container">
    <p style="font-size:2em"><strong>Patient Assessment:</strong></p>
    <div class="row align-items-start">
      <div class="col-md-6">
        <p><strong>Physical Video:</strong></p>
          <% if @form.physical_video_file_name.present? %>
            <% gcs_service = GoogleCloudStorageService.new %>
            <% signed_url = gcs_service.generate_signed_url_for_viewing(@form.physical_video_file_name) %>
              <div class="video-container text-center mt-3">
                <%= video_tag signed_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
              </div>
              <br>
        <p><strong>Physical Video AI Assessment:</strong></p>
            <% ai_file = @form.physical_video_file_name.split('.')[0] + '_AI.mp4' %>
            <% ai_url = gcs_service.generate_signed_url_for_viewing(ai_file) %>
            <div class="video-container text-center mt-1">
              <%= video_tag ai_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
            </div>
        <% else %>
          <p>null</p>
        <% end %>
      </div>
      <div class="col-md-6">
        <p><strong>AI Primary Physical Assessment: </strong><%= @form.physical_primary_assessment.presence || "Pending Assessment" %></p>
        <p><strong>Physical Assessment: </strong><%= @form.physical_assessment.presence || "Pending Assessment" %></p>
        <%= form_with(model: @form, url: @form.persisted? ? edit_physical_assessment_form_path(@form) : edit_physical_assessment_forms_path, method: :patch, local: true, html: { multipart: true }) do |form| %>
        <fieldset>
          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Good", class: "form-check-input", id: "good_phy", checked: @form.physical_assessment == "Good", :required => false %>
            <%= form.label "good_phy", class: "form-check-label", for: "good_phy" do %>
              Good
            <% end %>
          </div>

          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Fair", class: "form-check-input", id: "fair_phy", checked: @form.physical_assessment == "Fair", :required => false %>
            <%= form.label "fair_phy", class: "form-check-label", for: "fair_phy" do %>
              Fair
            <% end %>
          </div>

          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Poor", class: "form-check-input", id: "poor_phy", checked: @form.physical_assessment == "Poor", :required => false %>
            <%= form.label "poor_phy", class: "form-check-label", for: "poor_phy" do %>
              Poor
            <% end %>
          </div>

          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Detailed Assessment Needed", class: "form-check-input", id: "others_phy", checked: !["Good", "Fair", "Poor", ""].include?(@form.physical_assessment) %>
            <%= form.label "others_phy", class: "form-check-label", for: "others_phy" do %>
              Detailed Assessment Needed:
            <% end %>
          </div>

          <br></br>

          <div class="form-check">
              
            <%= form.text_field :others_text, class: "form-control", id: "others_text_phy", placeholder: "Detailed Assessment here", style: "font-style: italic; height: 175px; width: 300 px;", value: (!["Good", "Fair", "Poor", ""].include?(@form.physical_assessment)) ? @form.physical_assessment : ''%>
          </div>

          <div class="d-flex justify-content-center mt-5 mb-5">
            <%= form.submit "Save", name: "commit", value: "Save", class: "btn btn-lg rounded-pill btn-green me-2", id: "save_phy", style: 'float: left; margin-right: 5px;'  %>

          </div>

          
        </fieldset>
      </div>
    </div>

  <% end %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ruby-app/app/views/admins/_physical_assessment.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninkatec Onboarding | Physical Assessment</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

</head>

<body>
  <div class="container">
    <p style="font-size:2em"><strong>Patient Assessment:</strong></p>
    <div class="row align-items-start">
      <div class="col-md-6">
        <p><strong>Physical Video:</strong></p>
          <% if @form.physical_video_file_name.present? %>
            <% gcs_service = GoogleCloudStorageService.new %>
            <% signed_url = gcs_service.generate_signed_url_for_viewing(@form.physical_video_file_name) %>
              <div class="video-container text-center mt-3">
                <%= video_tag signed_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
              </div>
              <br>
        <p><strong>Physical Video AI Assessment:</strong></p>
            <% ai_file = @form.physical_video_file_name.split('.')[0] + '_AI.mp4' %>
            <% ai_url = gcs_service.generate_signed_url_for_viewing(ai_file) %>
            <div class="video-container text-center mt-1">
              <%= video_tag ai_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
            </div>
        <% else %>
          <p>null</p>
        <% end %>
      </div>
      <div class="col-md-6">
        <p><strong>AI Primary Physical Assessment: </strong><%= @form.physical_primary_assessment.presence || "Pending Assessment" %></p>
        <p><strong>Physical Assessment: </strong><%= @form.physical_assessment.presence || "Pending Assessment" %></p>
        <%= form_with(model: @form, url: @form.persisted? ? edit_physical_assessment_form_path(@form) : edit_physical_assessment_forms_path, method: :patch, local: true, html: { multipart: true }) do |form| %>
        <fieldset>
          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Good", class: "form-check-input", id: "good_phy", checked: @form.physical_assessment == "Good", :required => false %>
            <%= form.label "good_phy", class: "form-check-label", for: "good_phy" do %>
              Good
            <% end %>
          </div>

          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Fair", class: "form-check-input", id: "fair_phy", checked: @form.physical_assessment == "Fair", :required => false %>
            <%= form.label "fair_phy", class: "form-check-label", for: "fair_phy" do %>
              Fair
            <% end %>
          </div>

          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Poor", class: "form-check-input", id: "poor_phy", checked: @form.physical_assessment == "Poor", :required => false %>
            <%= form.label "poor_phy", class: "form-check-label", for: "poor_phy" do %>
              Poor
            <% end %>
          </div>

          <div class="form-check form-check-inline">
            <%= form.radio_button :physical_assessment, "Detailed Assessment Needed", class: "form-check-input", id: "others_phy", checked: !["Good", "Fair", "Poor", ""].include?(@form.physical_assessment) %>
            <%= form.label "others_phy", class: "form-check-label", for: "others_phy" do %>
              Detailed Assessment Needed:
            <% end %>
          </div>

          <br></br>

          <div class="form-check">
              
            <%= form.text_field :others_text, class: "form-control", id: "others_text_phy", placeholder: "Detailed Assessment here", style: "font-style: italic; height: 175px; width: 300 px;", value: (!["Good", "Fair", "Poor", ""].include?(@form.physical_assessment)) ? @form.physical_assessment : ''%>
          </div>

          <div class="d-flex justify-content-center mt-5 mb-5">
            <%= form.submit "Save", name: "commit", value: "Save", class: "btn btn-lg rounded-pill btn-green me-2", id: "save_phy", style: 'float: left; margin-right: 5px;'  %>

          </div>

          
        </fieldset>
      </div>
    </div>

  <% end %>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ruby-app/app/views/admins/client_profile.js.erb
$("#meetings_calendar").html("<%= escape_javascript render(partial: 'meetings/calendar', locals:{meeting: @meetings, self_meetings:@attached_meetings}) %>");

ruby-app/app/views/admins/test.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Client Profile</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <style>
    video {
      width: 100%;
    }

    p {
      font-size: 1.5em;
    }

    .text-orange {
      color: #fd7e14;
    }

    .text-danger {
      color: red;
    }

    .disabled {
      pointer-events: none;
      opacity: 0.6;
    }

    .orange-tab {
      color: #fd7e14 !important;
    }

    #map {
      height: 400px;
      width: 100%;
    }
  </style>
</head>
<body>
  <div class="container my-5">
    <h1 id="address">670204</h1>
    <div id="map"></div>
  </div>

  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const address = document.getElementById('address').textContent;
      initMap(address);
    });

    function initMap(address) {
      const mapContainer = document.getElementById('map');
      const iframe = document.createElement('iframe');
      iframe.width = '100%';
      iframe.height = '400';
      iframe.style.border = 0;
      iframe.src = `https://www.google.com/maps/embed/v1/place?key=AIzaSyAaFDN9Fp4K1SLq5TCQVL0BwxfgMYz01u0&q=${address}`;
      mapContainer.appendChild(iframe);
    }
  </script>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>