ruby-app/config/routes.rb
# # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :meetings
  devise_for :users

  authenticated :user, lambda { |u| !u.admin? } do
    root 'patients#index', as: :user_root
  end

  authenticated :user, lambda { |u| u.admin? } do
    root 'admins#index', as: :admin_root
  end

  # For non-authenticated users, redirect them to a specific page, like a login page or a welcome page
  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :assessments, only: [:edit, :update]



  get '/search', to: "admins#search"

  resources :forms, controller: 'patients' do
    member do
      get 'edit_1', to: 'patients#edit_1'
      patch 'edit_1', to: 'patients#update_1'
      get 'edit_2', to: 'patients#edit_2'
      patch 'edit_2', to: 'patients#update_2'
      get 'edit_3', to: 'patients#edit_3'
      patch 'edit_3', to: 'patients#update_3'
      get 'edit_4', to: 'patients#edit_4'
      patch 'edit_4', to: 'patients#update_4'
      get 'edit_5', to: 'patients#edit_5'
      patch 'edit_5', to: 'patients#update_5'
      get 'edit_physical_assessment', to: 'admins#_physical_assessment'
      patch 'edit_physical_assessment', to: 'admins#update_physical_assessment'
      get 'edit_mental_assessment', to: 'admins#_mental_assessment'
      patch 'edit_mental_assessment', to: 'admins#update_mental_assessment'
      get 'edit_environment_assessment', to: 'admins#_environment_assessment'
      patch 'edit_environment_assessment', to: 'admins#update_environment_assessment'
      get 'client_profile', to: 'admins#client_profile'
      patch 'client_profile', to: 'admins#update_client_profile'

      get 'edit_patient_assessment', to: 'admins#_patient_assessment'
      patch 'edit_patient_assessment', to: 'admins#update_patient_assessment'

      get 'physical_assessment', to: 'assessments#physical', as: 'physical_assessment'

      patch 'update_submission_status', to: 'patients#update_submission_status'
      post 'generate_signed_url', to: 'patients#generate_signed_url'
    end

    collection do
      get 'edit_1', to: 'patients#edit_1'
      post 'edit_1', to: 'patients#update_1_collection'
      get 'edit_2', to: 'patients#edit_2'
      post 'edit_2', to: 'patients#update_2_collection'
      get 'edit_3', to: 'patients#edit_3'
      post 'edit_3', to: 'patients#update_3_collection'
      get 'edit_4', to: 'patients#edit_4'
      post 'edit_4', to: 'patients#update_4_collection'
      get 'edit_5', to: 'patients#edit_5'
      post 'edit_5', to: 'patients#update_5_collection'
      get 'show_error', to: 'patients#show_error'
    end
  end
end

ruby-app/app/models/meeting.rb
class Meeting < ApplicationRecord
    belongs_to :form, optional: true
    validates :title, :location, :start_time, presence: true

    def readable_day
        datetime = DateTime.parse(start_time.to_s)

        # Format the datetime object into custom format
        formatted_datetime = datetime.strftime("%a")

        # Return the formatted datetime string
        formatted_datetime
    end


    def readable_datetime
        datetime = DateTime.parse(start_time.to_s)

        # Format the datetime object into custom format
        formatted_datetime = datetime.strftime("%-d %B %Y, %l:%M%P")

        # Return the formatted datetime string
        formatted_datetime
    end

    def overflow_date
        formatted_datetime = "#{readable_day}, <br> #{readable_datetime}"
        formatted_datetime
    end

    def inline_date
        formatted_datetime = "#{readable_day}, #{readable_datetime}"
        formatted_datetime
    end

    def condensed_time
        datetime = DateTime.parse(start_time.to_s)

        # Extract the time part from the DateTime object
        time_part = datetime.strftime("%l:%M %p").strip

        # Return the formatted time string
        time_part
    end

    def past_date
        current_datetime = DateTime.now

        # Compare current_datetime with attribute_datetime
        current_datetime > start_time
    end

    def parsed_start_time
        "#{start_time.hour}:00"
    end

    def self.hours
        start_hour = 8  # Calendar starts at 08:00 AM
        end_hour = 22   # Calendar ends at 10:00 PM
        (start_hour..end_hour).map { |hour| "#{hour}:00" }
    end

    def hours
        timestamps = []

        # Define start and end times
        start_time = Time.parse("08:00")
        end_time = Time.parse("22:00")

        current_time = start_time

        # Iterate from start_time to end_time in steps of 1 hour
        while current_time <= end_time do
          # Format the current_time in military time format ("%H:%M")
          military_time = current_time.strftime("%H:%M")

          # Add to the timestamps array
          timestamps << military_time

          # Move to the next hour
          current_time += 1.hour
        end

        timestamps
    end
end

ruby-app/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy ]
  before_action :set_all_meetings

  # GET /meetings or /meetings.json
  def index
    if current_user.admin?
      @meetings = Meeting.all
    else
      @meetings = current_user.forms.includes(:meeting).map(&:meeting).compact
    end
    @meeting = Meeting.new()
    respond_to do |format|
      format.html
      format.json { render json: @meetings.to_json(include: { form: { only: [:id, :first_name, :last_name, :address] }})}
    end
  end

  # GET /meetings/1 or /meetings/1.json
  def show
    respond_to do |format|
      format.html
      format.json { render json: @meeting.to_json(include: :form)}
    end
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)
    respond_to do |format|
      if @meeting.save
        if @meeting.form_id.present?
          start_time = @meeting.start_time
          @form = Form.find(meeting_params[:form_id])
          begin
            MeetingMailer.schedule_meeting_email(@form, start_time).deliver_now
            flash[:message] = "Meeting scheduled and email sent successfully."
          rescue => e
            flash[:danger] = "There was an error sending the email: #{e.message}"
          end
          format.html { redirect_to client_profile_form_path(@form, status: 'Meeting Date Pending'), notice: "Meeting was successfully created." }
          format.json { render :show, status: :created, location: @meeting }
        elsif current_user.admin?
          format.html { redirect_to admin_root_path(start_date: DateTime.now), notice: "Meeting was successfully destroyed." }
          format.json { render :show, status: :created, location: @meeting }
        else
          format.html { redirect_to user_root_path, notice: "How did you do this." }
          format.json { head :no_content }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      old_start_time = @meeting.start_time
      if @meeting.update(meeting_params)
        if @meeting.form_id.present? &&@meeting.start_time != old_start_time
          new_start_time = @meeting.start_time
          @form = Form.find(@meeting.form_id)
          begin
            MeetingMailer.reschedule_meeting_email(@form, old_start_time, new_start_time).deliver_now
            flash[:message] = "Meeting rescheduled and Meeting Rescheduled email sent successfully."
          rescue => e
            flash[:danger] = "There was an error sending the email: #{e.message}"
          end
          
        end
        format.html { redirect_to meeting_url(@meeting), notice: "Meeting was successfully updated." }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    if @meeting.form
      @form = @meeting.form
      begin
        MeetingMailer.cancel_meeting_email(@form).deliver_now
        flash[:message] = "Meeting deleted and Meeting Cancellation email sent successfully."
      rescue => e
        flash[:danger] = "There was an error sending the email: #{e.message}"
      end
    end
    @meeting.destroy!

    respond_to do |format|
      if params[:origin] && @form
        format.html { redirect_to client_profile_form_path(@form), notice: "Meeting was successfully destroyed." }
        format.json { render json: {
            status: "Meeting was successfully destroyed."
          }
        }
      else
        if current_user.admin?
          format.html { redirect_to admin_root_path(start_date: DateTime.now), notice: "Meeting was successfully destroyed." }
          format.json { render json: {
            status: "Meeting was successfully destroyed."
          }
        }
        else
          format.html { redirect_to user_root_path, notice: "How did you do this." }
          format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def set_all_meetings
      @meetings = Meeting.where(
        start_time: Time.now.beginning_of_month.beginning_of_week..Time.now.end_of_month.end_of_week
      )
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      permitted_params = params.require(:meeting).permit(:title, :description, :location, :start_time, :form_id)
      if permitted_params[:start_time].present?
        permitted_params[:start_time] = permitted_params[:start_time].in_time_zone('Asia/Singapore')
      end
      permitted_params
    end
end

ruby-app/app/views/meetings/_calendar.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Forms</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>" async defer></script>
  <style>
    th {
      cursor: pointer;
    }
  </style>
</head>
<body>
  <div class="container">
    <% if params[:view] == 'monthly' %>
      <%= month_calendar(events: @meetings) do |date, meetings| %>
        <div class="day">
          <%= date.day %>
          <% meetings.each do |meeting| %>
            <div style="width: 150px; padding: 8px; padding-top: 2px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-align: center;">
              <%= link_to "#{truncate(meeting.title, length: 16)} #{meeting.condensed_time}", meeting_path(meeting), class: 'custom-link' %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <%= week_calendar(events: @meetings) do |date, meetings| %>
        <div class="day">
          <%= date.day %>
        </div>
          <% meetings.each do |meeting| %>
              <div style="width: 150px; padding: 8px; padding-top: 2px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-align: center;" >
                <%= link_to "#{truncate(meeting.title, length: 16)} #{meeting.condensed_time}", meeting_path(meeting), class: 'custom-link'%>
              </div>
          <% end %>
      <% end %>
    <% end %>
  </div>

</body>

ruby-app/app/views/meetings/_form.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Meeting</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        .container {
            max-width: 600px;
            margin-top: 2em;
        }
        .header-container {
            display: flex;
            align-items: center;
        }
    </style>
</head>
<body>
    <div class="container">
        <%= form_with(model: @meeting, local: true, html: { class: "mt-4" }) do |form| %>
            <% if @meeting.errors.any? %>
                <div class="alert alert-danger">
                    <h4><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h4>
                    <ul>
                        <% @meeting.errors.each do |error| %>
                            <li><%= error.full_message %></li>
                        <% end %>
                    </ul>
                </div>
            <% end %>

            <div class="mb-3">
                <%= form.label :title do %>
                    Meeting Title/Patient Name <span style="color: red;">*</span> 
                <% end %>
                <%= form.text_field :title, required: true, class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= form.label :description %>
                <%= form.text_area :description, class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= form.label :location do %>
                    Meeting Location <span style="color: red;">*</span> 
                <% end %>
                <%= form.text_area :location, required: true, class: "form-control" %>
            </div>

            <div class="mb-3">
                <%= form.label :start_time do %>
                    Meeting Start Time <span style="color: red;">*</span> 
                <% end %>
                <%= form.datetime_local_field :start_time, required: true, class: "form-control" %>
            </div>

            <div class="d-grid gap-2">
                <%= form.submit "Save Changes", class: "btn btn-success" %>
            </div>
        <% end %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

ruby-app/app/views/meetings/_index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Forms</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>" async defer></script>
  <style>
    th {
      cursor: pointer;
    }
  </style>
</head>
<body>
  <div class="container">
    <% if params[:view] == 'monthly' %>
      <%= month_calendar(events: @meetings) do |date, meetings| %>
        <div class="day">
          <%= date.day %>
          <% meetings.each do |meeting| %>
            <div style="width: 150px; padding: 8px; padding-top: 2px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-align: center;">
              <%= link_to "#{truncate(meeting.title, length: 16)} #{meeting.condensed_time}", meeting_path(meeting), class: 'custom-link' %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <%= week_calendar(events: @meetings) do |date, meetings| %>
        <div class="day">
          <%= date.day %>
        </div>
          <% meetings.each do |meeting| %>
              <div style="width: 150px; padding: 8px; padding-top: 2px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis; text-align: center;" >
                <%= link_to "#{truncate(meeting.title, length: 16)} #{meeting.condensed_time}", meeting_path(meeting), class: 'custom-link'%>
              </div>
          <% end %>
      <% end %>
    <% end %>
  </div>

</body>

ruby-app/app/views/meetings/_meeting.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= meeting.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= meeting.description %>
  </p>



  <p>
    <strong>Location:</strong>
    <%= meeting.location %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= meeting.start_time %>
  </p>


</div>

ruby-app/app/views/meetings/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Meeting</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <style>
        .container {
            max-width: 800px;
            margin-top: 2em;
        }
        .header-container {
            display: flex;
            align-items: center;
        }
        .icon-link {
            display: flex;
            align-items: center;
            text-decoration: none;
            color: inherit;
            margin-right: 10px;
        }
        .icon-link:hover {
            color: #0056b3;
        }
        p {
            font-size: 1.5em;
        }
    </style>
</head>
  <body>
    <div class="container">
      <div class="header-container mb-1 justify-content-between">
        <%= link_to meeting_path(@meeting, origin: 'edit'), class: 'btn' do %>
          <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
          </svg>
        <%end%>
        <h1>Edit Meeting</h1>
        <div class="d-flex justify-content-end">
            <%= link_to @meeting, class: "icon-link btn btn-secondary" do %>
                <i class="fas fa-user"></i> Client Information
            <% end %>
        </div>
      </div>

      <hr/>

      <%= render "form", meeting: @meeting %>
      
      <hr/>
      <div>
        <%= link_to "Show this meeting", @meeting, class: "icon-link btn btn-secondary" %>
        <% if current_user.admin? %>
          <%= link_to "Back to Dashboard", admin_root_path, class: "icon-link btn btn-secondary" %>
        <% else %>
          <%= link_to "Back to Dashboard", user_root_path, class: "icon-link btn btn-secondary" %>
        <% end %>
      </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

ruby-app/app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <% if current_user.admin? %>
    <%= link_to "Back to meetings", admin_root_path %>
  <% end %>
</div>

ruby-app/app/views/meetings/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Meeting Details</title>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <style>
        .container {
            max-width: 800px;
            margin-top: 2em;
        }
        .header-container {
            display: flex;
            align-items: center;
        }
        .icon-link {
            display: flex;
            align-items: center;
            text-decoration: none;
            color: inherit;
            margin-right: 10px;
        }
        .icon-link:hover {
            color: #0056b3;
        }
        
        p {
          font-size: 1.5em;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header-container mb-1 justify-content-between">
            <% if params[:origin] == 'edit' %>
                <%= link_to admin_root_path, class: "btn", id: "back_btn" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
                    </svg>
                <% end %>
            <% else %>
                <%= link_to :back, class: "btn", id: "back_btn" do %>
                    <svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="currentColor" class="bi bi-chevron-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0"/>
                    </svg>
                <% end %>
            <% end %>
            <h1 style="margin-left: 1em">Meeting Details</h1>
            <div class="d-flex justify-content-end">
                <%= link_to edit_meeting_path(@meeting), class: "icon-link btn btn-outline-primary" do %>
                    <i class="fas fa-edit"></i> Edit
                <% end %>
                <%= button_to @meeting, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" do %>
                    <i class="fas fa-trash-alt"></i> Delete
                <% end %>
            </div>
        </div>

        <hr/>

        <div class = "d-flex justify-content-between align-items-center">
          <h2 style = "margin-bottom: 0.5em;">Patient Name: <%= @meeting.title%></h2>
              <% if @meeting.form %>
                  <%= link_to client_profile_form_path(@meeting.form), class: "icon-link btn btn-secondary text-light", style:"margin-right: 0" do %>
                      <i class="fas fa-user"></i> Client Information
                  <% end %>
              <% end %>
        </div>

        <p class="card-text">
            <strong>Description:</strong> <%= @meeting.description %>
        </p>
        <p class="card-text">
            <strong>Location:</strong> <%= @meeting.location %>
        </p>
        <p class="card-text">
            <strong>Start time:</strong> <%= @meeting.start_time %>
        </p>
            </div>
        </div>
      </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    </body>
</html>