ruby-app/config/routes.rb
# # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

Rails.application.routes.draw do
  resources :meetings
  devise_for :users

  authenticated :user, lambda { |u| !u.admin? } do
    root 'patients#index', as: :user_root
  end

  authenticated :user, lambda { |u| u.admin? } do
    root 'admins#index', as: :admin_root
  end

  # For non-authenticated users, redirect them to a specific page, like a login page or a welcome page
  devise_scope :user do
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :assessments, only: [:edit, :update]



  get '/search', to: "admins#search"

  resources :forms, controller: 'patients' do
    member do
      get 'edit_1', to: 'patients#edit_1'
      patch 'edit_1', to: 'patients#update_1'
      get 'edit_2', to: 'patients#edit_2'
      patch 'edit_2', to: 'patients#update_2'
      get 'edit_3', to: 'patients#edit_3'
      patch 'edit_3', to: 'patients#update_3'
      get 'edit_4', to: 'patients#edit_4'
      patch 'edit_4', to: 'patients#update_4'
      get 'edit_5', to: 'patients#edit_5'
      patch 'edit_5', to: 'patients#update_5'
      get 'edit_physical_assessment', to: 'admins#_physical_assessment'
      patch 'edit_physical_assessment', to: 'admins#update_physical_assessment'
      get 'edit_mental_assessment', to: 'admins#_mental_assessment'
      patch 'edit_mental_assessment', to: 'admins#update_mental_assessment'
      get 'edit_environment_assessment', to: 'admins#_environment_assessment'
      patch 'edit_environment_assessment', to: 'admins#update_environment_assessment'
      get 'client_profile', to: 'admins#client_profile'
      patch 'client_profile', to: 'admins#update_client_profile'

      get 'edit_patient_assessment', to: 'admins#_patient_assessment'
      patch 'edit_patient_assessment', to: 'admins#update_patient_assessment'

      get 'physical_assessment', to: 'assessments#physical', as: 'physical_assessment'

      patch 'update_submission_status', to: 'patients#update_submission_status'
      post 'generate_signed_url', to: 'patients#generate_signed_url'
    end

    collection do
      get 'edit_1', to: 'patients#edit_1'
      post 'edit_1', to: 'patients#update_1_collection'
      get 'edit_2', to: 'patients#edit_2'
      post 'edit_2', to: 'patients#update_2_collection'
      get 'edit_3', to: 'patients#edit_3'
      post 'edit_3', to: 'patients#update_3_collection'
      get 'edit_4', to: 'patients#edit_4'
      post 'edit_4', to: 'patients#update_4_collection'
      get 'edit_5', to: 'patients#edit_5'
      post 'edit_5', to: 'patients#update_5_collection'
      get 'show_error', to: 'patients#show_error'
    end
  end
end

ruby-app/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
   include PatientsHelper

   before_action :set_form, only: [:show, :edit_1, :update_1, :edit_2, :update_2, :edit_3, :update_3, :edit_4, :update_4, :edit_5, :update_5]
   before_action :check_valid_params, only: [:show]
   before_action :authenticate_user!

  def show
    @form = Form.includes(:user, :meeting).find(params[:id])
    respond_to do |format|
        format.html
        format.json { render json: @form.to_json(include: :user)}
    end
  end


  def index
    @forms = current_user.forms.select(:id, :first_name, :last_name, :start_date, :submitted)
    @form = current_user.forms.build
    @user = current_user
    session[:form_origin] = 'index'

    respond_to do |format|
      format.html
      format.json { render json: @forms.to_json(include: { meeting: { only: [:id, :title, :location, :start_time] }})}
    end
  end

  # Step 1 of form creation
  def new
    @form = current_user.forms.build
    # session[:form_origin] = 'new'

    respond_to do |format|
      format.html
      format.json { render json: @form.to_json}
    end
  end

  # Save step 1 form data and move to step 2
  def create
    case params[:commit]
    when 'Save'
      if params[:form].present? && params[:form].except(:autofill_address).values.any?(&:present?)
        @form = current_user.forms.build(form_params_step1)
        if @form.save
          session[:form_origin] = 'new'
          if current_user.admin? && params[:form][:nok_email].present?
            if @form.transfer_to_new_user(:nok_email)
              # puts 'WOWW'
            else
              # puts ':(('
            end
          end
          redirect_to edit_1_form_path(@form), notice: 'Step 1 of form creation was successfully saved.'
        end
      end
    when 'Next'
      if params[:form].present? && params[:form].except(:autofill_address).values.any?(&:present?)
        @form = current_user.forms.build(form_params_step1)
        if @form.save
          if current_user.admin?
            if @form.transfer_to_new_user(:nok_email)
              # puts 'WOWW'
            else
              # puts ':(('
            end
          end
          redirect_to edit_2_form_path(@form), notice: 'Step 1 of form creation was successfully saved.'
        end
      else
        redirect_to edit_2_forms_path
      end
    else
      render :new
    end
  end

  # GET /forms/1/edit_1
  def edit_1
    respond_to do |format|
      format.html
      format.json do
        if @form.valid?
          render json: @form.to_json, status: :ok
        else
          render json: {
            error: 'Validation failed',
            messages: @form.errors.full_messages
          }, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH /forms/1/update_1
  def update_1
    case params[:commit]
    when 'Save'
      if params[:form].present? && params[:form].except(:autofill_address).values.any?(&:present?)
        if @form.update(form_params_step1)
          redirect_to edit_1_form_path(@form), notice: 'Step 1 of form creation was successfully saved.'
        end
      end
    when 'Next'
      if params[:form].present? && params[:form].except(:autofill_address).values.any?(&:present?)
        if @form.update(form_params_step1)
          redirect_to edit_2_form_path(@form), notice: 'Step 1 of form creation was successfully saved.'
        else
        redirect_to edit_2_form_path(@form), notice: 'No changes were made.'
        end
      else
        redirect_to edit_2_form_path(@form), notice: 'No changes were made.'
      end
    else
      render :edit_1
    end
  end

  #collection update 1
  def update_1_collection
    case params[:commit]
    when 'Save'
      if params[:form].present? && params[:form].except(:autofill_address).values.any?(&:present?)
        @form = current_user.forms.build(form_params_step1)
        if @form.save
          session[:form_origin] = 'new'
          redirect_to edit_1_form_path(@form), notice: 'Step 1 of form creation was successfully saved.'
        end
      end
    when 'Next'
      if params[:form].present? && params[:form].except(:autofill_address).values.any?(&:present?)
        @form = current_user.forms.build(form_params_step1)
        if @form.save
          redirect_to edit_2_form_path(@form), notice: 'Step 1 of form creation was successfully saved.'
        end
      else
        redirect_to edit_2_forms_path
      end
    else
      render :edit_1
    end
  end

  # GET /forms/1/edit_2
  def edit_2
    respond_to do |format|
      format.html
      format.json do
        if @form.valid?
          render json: @form.to_json, status: :ok
        else
          render json: {
            error: 'Validation failed',
            messages: @form.errors.full_messages
          }, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH /forms/1/update_2
  def update_2
    case params[:commit]
    when 'Save'
      if @form.update(form_params_step2)
        redirect_to edit_2_form_path(@form), notice: 'Form 2 was successfully updated.'
      end
    when 'Next'
      if params[:form].present? && params[:form].values.any?(&:present?)
        if @form.update(form_params_step2)
          redirect_to edit_3_form_path(@form), notice: 'Form 2 was successfully updated.'
        end
      else
        redirect_to edit_3_form_path(@form), notice: 'No changes were made.'
      end
    else
      render :edit_2
    end
  end

    #collection update 2
    def update_2_collection
      case params[:commit]
      when 'Save'
        if params[:form].present? && params[:form].values.any?(&:present?)
          @form = current_user.forms.build(form_params_step2)
          if @form.save
            session[:form_origin] = 'new'
            redirect_to edit_2_form_path(@form), notice: 'Step 2 of form creation was successfully saved.'
          end
        end
      when 'Next'
        if params[:form].present? && params[:form].values.any?(&:present?)
          @form = current_user.forms.build(form_params_step2)
          if @form.save
            redirect_to edit_3_form_path(@form), notice: 'Step 2 of form creation was successfully saved.'
          end
        else
          redirect_to edit_3_forms_path
        end
      else
        render :edit_2
      end
    end

  # GET /forms/1/edit_3
  def edit_3
    respond_to do |format|
      format.html
      format.json do
        if @form.valid?
          render json: @form.to_json, status: :ok
        else
          render json: {
            error: 'Validation failed',
            messages: @form.errors.full_messages
          }, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH /forms/1/update_3
  def update_3
    case params[:commit]
    when 'Save'
      if @form.update(form_params_step3)
        redirect_to edit_3_form_path(@form), notice: 'Form 3 was successfully updated.'
      end
    when 'Next'
      if @form.update(form_params_step3)
        redirect_to edit_4_form_path(@form), notice: 'Form 3 was successfully updated.'
      end
    else
      render :edit_3
    end
  end

  #collection update 1
  def update_3_collection
    case params[:commit]
    when 'Save'
      if params[:form].present? && params[:form].values.any?(&:present?)
        @form = current_user.forms.build(form_params_step3)
        if @form.save
          session[:form_origin] = 'new'
          redirect_to edit_3_form_path(@form), notice: 'Step 2 of form creation was successfully saved.'
        end
      end
    when 'Next'
      if params[:form].present? && params[:form].values.any?(&:present?)
        @form = current_user.forms.build(form_params_step3)
        if @form.save
          redirect_to edit_4_form_path(@form), notice: 'Step 2 of form creation was successfully saved.'
        end
      else
        redirect_to edit_4_forms_path
      end
    else
      render :edit_3
    end
  end

  # GET /forms/1/edit_4
  def edit_4
    respond_to do |format|
      format.html
      format.json do
        if @form.valid?
          render json: @form.to_json, status: :ok
        else
          render json: {
            error: 'Validation failed',
            messages: @form.errors.full_messages
          }, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH /forms/1/update_4
  def update_4
    form_id = params[:form_id]
    @form = Form.find(params[:id])
    Rails.logger.debug "Update 4 action triggered for form ##{@form.id}"
    Rails.logger.debug "Full params: #{params.inspect}"
    changes = params[:patient][:changes].to_s.strip if params[:patient].present?
    case changes
    when 'Upload Physical Video'
      @form.physical_video_file_name = "#{params[:patient][:filename]}.mp4"
      if @form.save
        Rails.logger.debug "Physical video file name updated: #{@form.physical_video_file_name}"
        render json: { success: true, message: 'Physical video uploaded successfully' }
      else
        render json: { error: 'Failed to save physical video' }, status: :unprocessable_entity
      end
    when 'Upload Mental Video'
      @form.mental_video_file_name = "#{params[:patient][:filename]}.mp4"
      if @form.save
        Rails.logger.debug "Mental video file name updated: #{@form.mental_video_file_name}"
        render json: { success: true, message: 'Mental video uploaded successfully' }
      else
        render json: { error: 'Failed to save mental video' }, status: :unprocessable_entity
      end
    when 'Save'
      # if params[:form].present?
        # upload_physical_video(@form, params[:form][:physical_video]) if params[:form][:physical_video].present?
        # upload_mental_video(@form, params[:form][:mental_video]) if params[:form][:mental_video].present?
        # redirect_to edit_4_form_path(@form)
      # end
      
    when 'Next'
      # if params[:form].present?

ruby-app/app/helpers/patients_helper.rb
module PatientsHelper
    def checked_conditions(area)
        @form.conditions.nil? ? false : @form.conditions.match(area)
    end

    def checked_services(area)
        @form.services.nil? ? false : @form.services.match(area)
    end

    def checked_languages(area)
        @form.languages.nil? ? false : @form.languages.match(area)
    end

    def button_classes(form)
        classes = ["btn btn-primary circular-button btn-blue"] * 6
        classes[0] = "btn btn-primary circular-button btn-outline-red" unless form.pg1_valid
        classes[1] = "btn btn-primary circular-button btn-outline-red" unless form.pg2_valid
        classes[2] = "btn btn-primary circular-button btn-outline-red" unless form.pg3_valid
        classes[3] = "btn btn-primary circular-button btn-outline-red" unless form.pg4_valid
        classes[4] = "btn btn-primary circular-button btn-outline-red" unless form.pg5_valid
        classes[5] = "btn btn-primary circular-button btn-outline-red" unless form.submittable
        classes
      end

    # def any_pending_assessments?(form)
    #     form.physical_assessment.blank? || form.mental_assessment.blank? || form.environment_assessment.blank?
    # end

    # def meeting_date_pending_and_no_start_time?(meeting)
    #     meeting.start_time.nil? || meeting.start_time.blank?
    # end

end

ruby-app/app/views/patients/show.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Form Details</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <style>

    .container{
      max-width: 800px;
    }
    .video-container {
      max-width: 300px; /* Maximum width for the container */
      margin-bottom: 10px; /* Space between videos */
    }
    .video-container video {
      max-width: 300px;
      max-height: 180px;
      width: 100%;
      height: auto;
    }
    .circular-button {
      border-radius: 50%;
      width: 40px;
      height: 40px;
    }
    .btn-blue {
      background-color: #253255;
      color: white;
    }
    .btn-outline-blue {
      border-color: #253255;
      color: #253255;
    }
    .steps .page {
      display: flex;
      justify-content: space-between;
      margin-bottom: 1rem;
    }
    .step {
      display: flex;
      flex-direction: column;
      align-items: center;
      text-align: center;
    }
    .step-label {
      margin-top: 0.5rem;
      font-size: 18px;
    }
    /* Container for centering the loader */
    #loadingIndicator_show {
      position: fixed; /* Fixed position to stay in place while scrolling */
      top: 50%; /* Center vertically */
      left: 50%; /* Center horizontally */
      transform: translate(-50%, -50%); /* Adjust for exact center */
      z-index: 1000; /* Ensure it appears above other content */
    }

    /* Content wrapper to center the dot */
    .loading-content {
      display: flex;
      align-items: center;
      justify-content: center;
    }

    /* Pulsing dot loader */
    .pulsing-dot {
      position: absolute;
      width: 200px;
      height: 200px;
      background-color: #3498db;
      border-radius: 50%;
      animation: pulse 1.5s infinite ease-in-out;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    /* Loading text */
    .loading-text {
      color: #000000; /* Set text color for contrast */
      font-size: 30px;
      font-weight: bold;
      text-align: center;
    }

    /* Pulse animation */
    @keyframes pulse {
      0% {
        transform: scale(1);
        opacity: 1;
      }
      50% {
        transform: scale(1.5);
        opacity: 0.5;
      }
      100% {
        transform: scale(1);
        opacity: 1;
      }
    }
  </style>
</head>
<body>
  <div class="container mt-5">
    <div class="steps">
      <div class="page">
        <div class="step">
          <%= button_to '1', @form.persisted? ? edit_1_form_path(@form) : edit_1_forms_path, method: :get, class: @form.persisted? ? @valid_button_classes[0] : "btn btn-primary circular-button btn-outline-blue" %>
          <p class="step-label">Patient Details</p>
        </div>
        <div class="step">
          <%= button_to '2', @form.persisted? ? edit_2_form_path(@form) : edit_2_forms_path, method: :get, class: @form.persisted? ? @valid_button_classes[1] : "btn btn-primary circular-button btn-outline-blue" %>
          <p class="step-label">Medical Conditions</p>
        </div>
        <div class="step">
          <%= button_to '3', @form.persisted? ? edit_3_form_path(@form) : edit_3_forms_path, method: :get, class: @form.persisted? ? @valid_button_classes[2] : "btn btn-primary circular-button btn-outline-blue" %>
          <p class="step-label">Service Required</p>
        </div>
        <div class="step">
          <%= button_to '4', @form.persisted? ? edit_4_form_path(@form) : edit_4_forms_path, method: :get, class: @form.persisted? ? @valid_button_classes[3] : "btn btn-primary circular-button btn-outline-blue" %>
          <p class="step-label">Patient Assessment</p>
        </div>
        <div class="step">
          <%= button_to '5', @form.persisted? ? edit_5_form_path(@form) : edit_5_forms_path, method: :get, class: @form.persisted? ? @valid_button_classes[4] : "btn btn-primary circular-button btn-outline-blue" %>
          <p class="step-label">Home Assessment</p>
        </div>
        <div class="step">
          <button type="button" class="btn btn-primary circular-button btn-blue" id="btn6" data-action="click->form#validateForm">6</button>
          <p class="step-label">Summary Page</p>
        </div>
      </div>
      <div data-form-target="popup"></div>
    </div>

    <h1 class="text-center mb-4">Form Summary</h1>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title" style="font-size: 1.5em;">Personal Information</h5>
        <p class="card-text"><strong>NOK Full Name:</strong> <%= "#{@form.nok_first_name} #{@form.nok_last_name}" %></p>
        <p class="card-text"><strong>NOK Contact No.:</strong> <%= @form.nok_contact_no %></p>
        <p class="card-text"><strong>NOK Address:</strong> <%= @form.nok_address %></p>
        <p class="card-text"><strong>NOK Email Address:</strong> <%= @form.nok_email %></p>
        <% if !@form.user.present? %>
          <p class="card-text"><strong>Associated User not found</strong></p>
        <% end %>
        <p class="card-text"><strong>First Name:</strong> <%= @form.first_name %></p>
        <p class="card-text"><strong>Last Name:</strong> <%= @form.last_name %></p>
        <p class="card-text"><strong>Gender:</strong> <%= @form.gender %></p>
        <p class="card-text"><strong>Date of Birth:</strong> <%= @form.date_of_birth %></p>
        <p class="card-text"><strong>Address:</strong> <%= @form.address %></p>
        <p class="card-text"><strong>Relationship:</strong> <%= @form.relationship %></p>
        <p class="card-text"><strong>Hobbies:</strong> <%= @form.hobbies %></p>
        <p class="card-text"><strong>Languages Spoken:</strong> <%= @form.languages %></p>
        <p class="card-text"><strong>Other Languages Spoken:</strong> <%= @form.languages_other %></p>
        
        <hr/>

        <h5 class="card-title" style="font-size: 1.5em;">Health Information</h5>
        <p class="card-text"><strong>Height:</strong> <%= @form.height %></p>
        <p class="card-text"><strong>Weight:</strong> <%= @form.weight %></p>
        <p class="card-text"><strong>Conditions:</strong> <%= @form.conditions %></p>
        <p class="card-text"><strong>Other Conditions:</strong> <%= @form.conditions_other %></p>
        <p class="card-text"><strong>Medication:</strong> <%= @form.medication %></p>
        <p class="card-text"><strong>Hospitalised recently:</strong> <%= @form.hospital.nil? ? "" : (@form.hospital ? "Yes" : "No") %></p>

        <% if @form.discharge_summary.attached? %>
          <div class="mt-3">
            <p class="card-text"><strong>Discharge Summary Preview:</strong></p>
            <%= image_tag @form.discharge_summary, class: "img-thumbnail", style: "max-width: 300px;" %>
          </div>
        <% end %>
        
        <hr/>

        <h5 class="card-title" style="font-size: 1.5em;">Service Information</h5>
        <p class="card-text"><strong>Services:</strong> <%= @form.services %></p>
        <p class="card-text"><strong>Other Services:</strong> <%= @form.services_other %></p>
        <p class="card-text"><strong>Start Date:</strong> <%= @form.start_date %></p>
        <p class="card-text"><strong>End Date:</strong> <%= @form.end_date %></p>
      </div>
      <!-- Row for Videos -->
      <div class="row mt-3 align-content-center" height: 50em;>
        <div class="col-md-4">
          <div class="video-container text-center">
            <p>Physical Video:</p>
            <% if @form.physical_video_file_name.present? %>
              <% gcs_service = GoogleCloudStorageService.new %>
              <% signed_url = gcs_service.generate_signed_url_for_viewing(@form.physical_video_file_name) %>
                <div class="video-container text-center mt-3">
                  <%= video_tag signed_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
                </div>
              <% if @form.submitted %>
                <p class="card-text"><strong>Primary Physical Assessment:</strong> <%= @form.physical_primary_assessment %></p>
                <p class="card-text"><strong>Final Physical Assessment:</strong> <%= @form.physical_assessment %></p>
              <% end %>
            <% else %>
              <p>No physical video attached</p>
            <% end %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="video-container text-center">
            <p>Mental Video:</p>
            <% if @form.mental_video_file_name.present? %>
              <% gcs_service = GoogleCloudStorageService.new %>
              <% signed_url = gcs_service.generate_signed_url_for_viewing(@form.mental_video_file_name) %>
                <div class="video-container text-center mt-3">
                  <%= video_tag signed_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
                </div>
              <% if @form.submitted %>
                <p class="card-text"><strong>Primary Mental Assessment:</strong> <%= @form.mental_primary_assessment %></p>
                <p class="card-text"><strong>Final Mental Assessment:</strong> <%= @form.mental_assessment %></p>
              <% end %>    
            <% else %>
              <p>No mental video attached</p>
            <% end %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="video-container text-center">
            <p>Environment Video:</p>
            <% if @form.environment_video_file_name.present? %>
              <% gcs_service = GoogleCloudStorageService.new %>
              <% signed_url = gcs_service.generate_signed_url_for_viewing(@form.environment_video_file_name) %>
                <div class="video-container text-center mt-3">
                  <%= video_tag signed_url, controls: true, class: "img-thumbnail video-preview rounded-video" %>
                </div>
              <% if @form.submitted %>
                <p class="card-text"><strong>Primary Environment Assessment:</strong> <%= @form.environment_primary_assessment %></p>
                <p class="card-text"><strong>Final Environment Assessment:</strong> <%= @form.environment_assessment %></p>
              <% end %>
            <% else %>
              <p>No environment video attached</p>
            <% end %>
          </div>
        </div>
      </div>

      <div class="d-flex  justify-content-center mt-5 mb-5">
        <%= link_to "Back", edit_5_form_path(@form), class: "btn btn-lg btn-outline-black rounded-pill me-2" %>
        <%= form_tag(update_submission_status_form_path(@form), method: :patch) do %>
          <% if @form.submitted? %>
            <%= submit_tag 'Update', class: "btn btn-lg rounded-pill btn-green me-2", disabled: !@form.submittable, id: "submitButton" %>
          <% else %>
            <%= submit_tag 'Submit', class: "btn btn-lg rounded-pill btn-green me-2", disabled: !@form.submittable, id: "submitButton" %>
          <% end %>
        <% end %>
        <% if current_user.admin? %>
          <%= link_to 'Back to List', admin_root_path, class: 'btn btn-lg btn-outline-black rounded-pill' %>
        <% else %>
          <%= link_to 'Back to List', user_root_path, class: 'btn btn-lg btn-outline-black rounded-pill' %>
        <% end %>
      </div>
    </div>
    <div id="loadingIndicator_show" class="loading-container" style="display: None;">
      <div class="loading-content">
        <div class="pulsing-dot"></div>
        <div class="loading-text">Processing...</div>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@hotwired/stimulus/dist/stimulus.umd.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var form = document.querySelector('form'); 
      var loadingIndicator = document.getElementById('loadingIndicator_show');
      
        document.getElementById('submitButton').addEventListener('click', function(event) {
          // Show the loading indicator
          loadingIndicator.style.display = 'block';
        });
      });
  </script>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</body>
</html>

ruby-app/app/views/patients/show_error.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ninkatec Onboarding | Form 5</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
<body>
  <div class="container">
    <!-- Steps Bar -->
    <div class="steps">
      <div class="page">
        <%= button_to '1', edit_1_forms_path, method: :get, class: "btn btn-primary circular-button btn-outline-blue" %>
        <%= button_to '2', edit_2_forms_path, method: :get, class: "btn btn-primary circular-button btn-outline-blue" %>
        <%= button_to '3', edit_3_forms_path, method: :get, class: "btn btn-primary circular-button btn-outline-blue" %>
        <%= button_to '4', edit_4_forms_path, method: :get, class: "btn btn-primary circular-button btn-outline-blue" %>
        <%= button_to '5', edit_5_forms_path, method: :get, class: "btn btn-primary circular-button btn-outline-blue" %>
        <button type="button" class="btn btn-primary circular-button btn-blue">6</button>
      </div>
    </div>

    <!-- Title -->
    <h1>Summary Page</h1>
    
    <!-- Error Message -->
    <div class="alert alert-warning" role="alert">
      No form details available. Save or enter some details first.
    </div>

    <!-- Navigation Buttons -->
    <div class="d-flex justify-content-center mt-5 mb-5">
      <% if current_user.admin? %>
        <%= link_to 'Back to List', admin_root_path, class: 'btn btn-lg btn-outline-black rounded-pill' %>
      <% else %>
        <%= link_to 'Back to List', user_root_path, class: 'btn btn-lg btn-outline-black rounded-pill' %>
      <% end %>
    </div>
    
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

ruby-app/app/views/patients/table.html.erb
<!-- app/views/forms/table.html.erb -->
<h1>Forms Table</h1>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Start Date</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.first_name %></td>
        <td><%= form.last_name %></td>
        <td><%= form.start_date %></td>
        <td><%= link_to 'Edit', edit_form_path(form) %></td>
      </tr>
    <% end %>
  </tbody>
</table>